#!/bin/bash 
ARCHIVO=$1
ARCHIVO=$2

for ARCHIVO in $ARCHIVO
do


if [ -e $ARCHIVO ]; THEN 
	echo "$ARCHIVO existe"
else
	echo "$ARCHIVO no existe"
	continue
fi

if [ -f $ARCHIVO ]; then
	echo "$ARCHIVO es un archivo regular"
fi

if [ -r $ARCHIVO ]; then
	echo "$USER tiene permiso de lectura sobre $ARCHIVO"
fi

if [ -w $ARCHIVO ]; then
	echo "$USER tiene permisos de escritura sobre $ARCHIVO"
fi

if [ -x $ARCHIVO ]; then
	echo "$USER tiene permiso de ejecucion sobre $ARCHIVO"
fi
done

echo FIN

